### ISSUE TITLE
Set up Kanban Board

### ISSUE THREAD

**Issue by asharanjith** [asharanjith/Javascript-Group-Capstone#34]
For viewing the project link, [click here](https://github.com/users/asharanjith/projects/1)

We are a team of two,
 Student A- Simeon Trust(Trust-007)
Student B - Asha S Vijayan(asharanjith)

**Comment by Abenezer-Tilahun** [comment]
Hi @asharanjith  , 

Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍


![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️

- [ ] Kindly make sure that link to their GitHub project is working, the link is broken.

![Capture](https://user-images.githubusercontent.com/93598189/203052602-79ed1f83-4ed4-4d9e-9c04-5749fd499a61.PNG)

_Check the comments below the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Qoosim** [comment]
#   *Status: Approved* :tada: :heavy_check_mark: 

Hi @team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
-  Correct Kanban board set up. :heavy_check_mark: 
-  Tasks assigned correctly. :heavy_check_mark: 
-  Irrelevant cards removed. :heavy_check_mark: 

![](https://camo.githubusercontent.com/933d15a5d5acd62a4c99c1e2b391cacfbfe61154e349c4af39c9a99d8d10caab/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f3236444f6f4477644e474b416736554b492f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
